config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about' => 'about#index'
  get 'refer' => 'refer#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :jobs
  
 resources :users

  resources :posts do
    resources :comments
  end

  resources :conversations do
    resources :messages
  end


  resources :cvs, only: [:index, :show, :new, :create, :destroy]

  get "profile/:username" => "users#show", as: :profile

end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :user

    include PgSearch::Model
        pg_search_scope :search_by_job_title_and_location,
        against: [ :job_title, :location ],
        using: {
        tsearch: { prefix: true } # <-- now `superman batm` will return something! Partial words allowed.
        }

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index

    if params[:query].present?
      @jobs = Job.search_by_job_title_and_location(params[:query])
    else
      @jobs = Job.all.order("created_at DESC")

  
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user = current_user
    
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
        @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:job_title, :location, :description, :skills)
    end

end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
    <% if job.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>
  
        <ul>
          <% job.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label "Company Logo" %>
      <%= form.file_field :avatar %>
    </div>
  
    <div class="field">
      <%= form.label :job_title %>
      <%= form.text_field :job_title %>
    </div>

    <div class="field">
      <%= form.label :location %>
      <%= form.text_field :location %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>

    <div class="field">
      <%= form.label :skills %>
      <%= form.text_field :skills %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container text-center">
  <h1>Jobs</h1>
</div>

<%= form_tag jobs_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Search for a Job Title"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<div class="container">
  <div class="row">
    
      <div class="card-deck">
        <% @jobs.each do |job| %>
          <div class="card">
            <img class="card-img-top" src="..." alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">Job Title: <%= link_to job.job_title, job %> </h5>
              <p class="card-text">Location: <%= job.location %></p>
              <p class="card-text">Description: <%= job.description %></p>
              <p class="card-text">Skills needed: <%= job.skills %></p>
              <%= link_to 'Edit', edit_job_path(job) %>
              <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        <% end %>
      
      
        
      
        
      </div>
  </div>
</div>
    

app/views/jobs/new.html.erb
<h1>Create Job Profile</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Job Title:</strong>
  <%= @job.job_title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @job.location %>
</p>

<p>
  <strong>Job Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @job.skills %>
</p>

<%= link_to 'Refer', "#", class: "btn btn-success" %>
<%= link_to 'Edit', edit_job_path(@job), class: "btn btn-light" %> |
<%= link_to 'Show Open Positions', jobs_path, class: "btn btn-secondary" %>