config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about' => 'about#index'
  get 'refer' => 'refer#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :jobs
  
 resources :users

  resources :posts do
    resources :comments
  end

  resources :conversations do
    resources :messages
  end


  resources :cvs, only: [:index, :show, :new, :create, :destroy]

  get "profile/:username" => "users#show", as: :profile

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_one_attached :avatar
  has_many :jobs
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :cv

  validate :correct_cv_mime_type

  def correct_cv_mime_type
    if cv.attached? && !document.content_type.in?(%w(application/pdf))
      document.purge # delete the uploaded file
      errors.add(:cv, 'Must be a PDF file')
    end
  end

  acts_as_voter

  has_many :conversations
  has_many :messages, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end

  include PgSearch::Model
  pg_search_scope :search_by_name_and_job,
    against: [ :name, :current_job ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something! Partial words allowed.
    }


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    # before_action :set_user, only: [:show]


def index
    # user profiles feed

    if params[:query].present?
        @users = User.search_by_name_and_job(params[:query])
    else
        @users = User.all
end

def show
    # user profile
    @user = User.find(params[:id])
end



private

# def set_user
  # @user = User.find(params[:username])
# end

def user_params
    params.require(:user).permit(:first_name, :last_name, :bio, :cv)
end

end

app/views/users/index.html.erb
<div class="container">
  <h1>Profiles</h1>
</div>

<%= form_tag users_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a Refer Profile"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<div class="container">
  <div class="row">
    
      <div class="card-deck">
        <% @users.each do |user| %>
          <div class="card">
            <img class="card-img-top" src="..." alt="Card image cap">
            <div class="card-body">
              
              <h5 class="card-title"><%= link_to user.full_name, user_path(user) %></h5>
              <p class="card-text"><%= user.current_job %></p>
              <p class="card-text"><%= user.bio %></p>
            
            </div>
          </div>
        <% end %>
      </div>
    
  </div>
</div>

app/views/users/show.html.erb
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h2 class="card-title"><strong><%= @user.full_name %></strong></h2>
    <p class="card-text"><%= @user.bio %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Current Job</li>
  </ul>
  <div class="card-body">
    <div class="buttons">
      <%= link_to "Edit Profile", edit_user_registration_path, class: "bth btn-success" %>
    </div>
    <div class="buttons">
      <%= link_to "Upload Resume", new_cv_path, class: "bth btn-success" %>
    </div>
    <div class="buttons">
      <%= link_to "View Resume", cv_path(current_user), class: "bth btn-success" %>
    </div>
  </div>
</div>