config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about' => 'about#index'
  get 'refer' => 'refer#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :jobs
  
 resources :users

  resources :posts do
    resources :comments
  end

  resources :conversations do
    resources :messages
  end


  resources :cvs, only: [:index, :show, :new, :create, :destroy]

  get "profile/:username" => "users#show", as: :profile

end

app/models/post.rb
class Post < ApplicationRecord

  validates_presence_of :content
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  acts_as_votable

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    respond_to :js, :html, :json

def index
    @posts = Post.all
end

def new
    @post = Post.new
end

def show
  @comments = @post.comments
end

def create

    @post = Post.new(post_params)
    @post.user_id = current_user.id
    
    if @post.save
      redirect_to posts_path(@post)
    else
      render :new
    end
  end

def like
  @post = Post.find(params[:id])
    if params[:format] == 'like'
      @post.liked_by current_user
    elsif params[:format] == 'unlike'
      @post.unliked_by current_user
    end
end


private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/views/posts/_form.html.erb
<div class="row">
    <div class="col-sm-6">
        <%= form_for @post do |form| %>
            <div class="form-group">
                <%= label_tag :title %>
                <%= form.text_field :title, class: "form-control" %>
            </div>
            <div class="form-group">
                <%= label_tag :content %>
                <%= form.text_area :content, class: "form-control" %>
            </div>
            <%= form.submit "Post", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Edit Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<h1>Posts</h1>

<div class="container">
    <% @posts.each do |post| %>
      <div class="card">
        <div class="card-body">
          <strong><%= link_to post.title, post_path(post)  %></strong>
          <br>
          <%= simple_format post.content %>
          <br>
        </div>
      </div>
    <% end %>
</div>
  

app/views/posts/new.html.erb
<div class="container">
  <h1>New Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="card">
  <div class="card-body">
    <h2><%= @post.title %></h2>
    <p><%= simple_format @post.content %></p>
    <strong><p>Comments</p></strong>
    <% @comments.each do |comment| %>
    <p><%= simple_format comment.content %></p>
    <% end %>
    <%= link_to "Comment", new_post_comment_path(@post), class: "btn btn-primary" %>
  </div>
</div>